levels = [[
    "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
    "R>                                   R",
    "R>                                  FR",
    "R44444RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
    "R    RR                              R",
    "R                                    R",
    "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR    <R",
    "R                                 R  R",
    "RU                                 ^^R",
    "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",],
    [
    "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
    "R     R               VV  V   V  VVVVR",
    "R     R                              R",
    "R  0R   R      0  R                  R",
    "R   R   R   0  0  R> P     E     P   R",
    "R0  R000R   0     R> PPPPPPPPPPPPP   R",
    "RU  R^^^R^^^^^^^^^R^^^^^^^^^^^^^^R  FR",
    "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",],
    [
    "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
    "R                                                                R",
    "R                                                                R",
    "R                                                                R",
    "R                                                                R",
    "R                                                                R",
    "R                                                                R",
    "R                                                                R",
    "R                                                                R",
    "R                                                                R",
    "R                P  E    P                                       R",
    "R           ^    PPPPPPPPP                                       R",
    "R F   RWWWWWR    VVVVVVV    4R                                   R",
    "RRRRRRRRRRRRR              33RR                                  R",
    "R                         222RRR                                 R",
    "R               ^        1111RRRR                                R",
    "R  U            R    E  00000RRRRR                               R",
    "RRRRRRRRWWWWWRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"]
]
